[package]
name = "pallet-election-provider-multi-block"
version = "4.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "PALLET two phase election providers"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
static_assertions = "1.1.0"
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4.14", default-features = false }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }

frame-support = { version = "4.0.0-dev", default-features = false, path = "../support" }
frame-system = { version = "4.0.0-dev", default-features = false, path = "../system" }

sp-io = { default-features = false, path = "../../primitives/io" }
sp-std = { default-features = false, path = "../../primitives/std" }
sp-core = { default-features = false, path = "../../primitives/core" }
sp-runtime = { default-features = false, path = "../../primitives/runtime" }
sp-npos-elections = { default-features = false, path = "../../primitives/npos-elections" }
sp-arithmetic = { default-features = false, path = "../../primitives/arithmetic" }
frame-election-provider-support = { version = "4.0.0-dev", default-features = false, path = "../election-provider-support" }

# Optional imports for benchmarking
frame-benchmarking = { version = "4.0.0-dev", default-features = false, path = "../benchmarking", optional = true }
rand = { version = "0.7.3", default-features = false, optional = true, features = ["alloc", "small_rng"] }

[dev-dependencies]
paste = "1.0.3"
parking_lot = "0.12.0"
rand = { version = "0.8.5" }
hex-literal = "0.3.1"
substrate-test-utils = { path = "../../test-utils" }
sp-tracing = { path = "../../primitives/tracing" }
frame-election-provider-support = { features = ["runtime-benchmarks"], path = "../election-provider-support" }
pallet-balances = { path = "../balances" }
frame-benchmarking = { path = "../benchmarking" }

[features]
default = ["std"]
std = [
	"codec/std",
	"log/std",
	"scale-info/std",

	"frame-support/std",
	"frame-system/std",

	"sp-io/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-npos-elections/std",
	"sp-arithmetic/std",
	"frame-election-provider-support/std",
	"log/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"rand",
]
try-runtime = ["frame-support/try-runtime"]
